= Applicative Functor in Java: An Experiment
Manuel Paccagnella <manuel.paccagnella@warda.it>
2016-06-x
:toc:
:source-highlighter: pygments
:icons: font

== Abstract
...

== Experiment setup

. Explain the problem (with types)
. Ask to implement a solution
. Show the solution that uses the applicative functor without explaining anything (don't mention the applicative functor!), and let the test subject read the code and understand how it works. This phase must be time-boxed, and the subject must have http://www.functionaljava.org/javadoc/4.5/functionaljava/index.html[API documentation] available.

== Problem description

We have to write a _function_ to increment a population:

[source,haskell]
----
incrementPopulation :: [Man] -> [Woman] -> [Child]
----

To implement this function, we can use another one:

[source,haskell]
----
reproduce :: Man -> Woman -> [Child]
----

.General problem
****
This problem is a specific _instance_ of a more general one:

[source,haskell]
----
-- We need:
f :: [a] -> [b] -> [c]
-- Using:
g :: a -> b -> [c]
----

In other words, `f` has to apply `g` to the https://en.wikipedia.org/wiki/Cartesian_product[cartesian product] of the input `a` and `b` values.
****

== Rules of the game

The test subject has 15-20 minutes to implement a solution to this problem. The rules are:

* The solution must be written in Java. Better if in Java 8+.
* Can be used the library http://www.functionaljava.org/[Functional Java].

To simplify the code:

* `Man`, `Woman` and `Child` types can be defined by a simple `String` (their name):
+
[source,haskell]
----
data Man = Man String deriving (Eq, Show)
data Woman = Woman String deriving (Eq, Show)
data Child = Child String deriving (Eq, Show)
----
+
* Names can be random https://en.wikipedia.org/wiki/Universally_unique_identifier[UUID]s.
* The number of children for every `reproduce` call is a random number between 0 and 6.
* If typed in an IDE, the code *must compile*. If this is the case, it's better to setup the infrastructure (project, compilation, dependencies, etc.) beforehand, or at least just before the actual implementation time-box. 

==  Solution using an applicative functor

[source,java]
----
private static List<Child> incrementPopulation(List<Man> men, List<Woman> women) {
  List<F<Woman, List<Child>>> fertileMen = men.map(reproduce());
  return List.join(women.apply(fertileMen));
}

private static F<Man, F<Woman, List<Child>>> reproduce() {
  return man -> woman -> 
    range(0, randomNumberBetween(0, 6))+1).map(n -> UUID.randomUUID()).map(UUID::toString);    
}
----
