= Applicative Functor in Java: An Experiment
Manuel Paccagnella <manuel.paccagnella@warda.it>
Rev:3, 2016-06-24
:toc:
:source-highlighter: pygments
:icons: font

== Abstract
This document describes an experiment to test the clarityfootnote:[Clarity is inherently _subjective_, as the results of this experiment.] of the type class https://wiki.haskell.org/Typeclassopedia#Applicative[applicative functor] as used in functional Java 8+ code.

== Experiment setup

Prerequisites:

* A test subject (can be a single developer or a group).
    * It helps if the test subject(s) have a basic understanding of Java 8 and of functional programming.
* A couple of slides to explain the problem and the rules.
* Functional Java http://www.functionaljava.org/javadoc/4.5/functionaljava/index.html[API documentation]
* (Optional) a ready to use project template.

The experiment has the following steps:

. Explain the problem (with types)
. Ask to implement a solution
. Show the solution that uses the applicative functor without explaining anything (don't mention the applicative functor!), and let the test subject read the code and understand how it works. This phase must be time-boxed, and the subject must have http://www.functionaljava.org/javadoc/4.5/functionaljava/index.html[API documentation] available.

== Problem description

We have to write a _function_ to increment a population:

[source,haskell]
----
incrementPopulation :: [Man] -> [Woman] -> [Child]
----

To implement this function, we can use another one:

[source,haskell]
----
reproduce :: Man -> Woman -> [Child]
----

Since this is a promiscuous population, _every man can mate with every woman_.

.General problem
****
This problem is a specific _instance_ of a more general one:

[source,haskell]
----
-- We need:
f :: [a] -> [b] -> [c]
-- Using:
g :: a -> b -> [c]
----

In other words, `f` has to apply `g` to the https://en.wikipedia.org/wiki/Cartesian_product[cartesian product] of the input `a` and `b` values.
****

== Rules of the game

The test subject has 15-20 minutes to implement a solution to this problem. The rules are:

* The solution must be written in Java. Better if in Java 8+.
* Can be used the library http://www.functionaljava.org/[Functional Java].

To simplify the code:

* `Man`, `Woman` and `Child` types can be defined by a simple `String` (their name):
+
[source,haskell]
----
data Man = Man String deriving (Eq, Show)
data Woman = Woman String deriving (Eq, Show)
data Child = Child String deriving (Eq, Show)
----
+
* Names can be random https://en.wikipedia.org/wiki/Universally_unique_identifier[UUID]s.
* The number of children created for every `reproduce` call is 2.
* If typed in an IDE, the code *must compile*. If this is the case, it's better to setup the infrastructure (project, compilation, dependencies, etc.) beforehand, or at least just before the actual implementation time-box. 

==  Solution using an applicative functor

[source,java]
----
private static List<Child> incrementPopulation(List<Man> men, List<Woman> women) {
  List<F<Woman, List<Child>>> fertileMen = men.map(reproduce());
  return List.join(women.apply(fertileMen));
}

private static F<Man, F<Woman, List<Child>>> reproduce() {
  return man -> woman -> 
    list(UUID.randomUUID(), UUID.randomUUID())
    .map(UUID::toString)
    .map(Child::child);
}
----

== Revisions

|===
|Revision | Date | Changes 

| 3
| 2016-06-24
| Clarified reproduction rules.

| 2
| 2016-06-17
| Simplified rules.

| 1
| 2016-06-17
| First version.

|===
